### ISSUE TITLE
Change or disable rules

### ISSUE THREAD

**Issue by rkarnia** [racodond/sonar-css-plugin#100]
You know why I'm not able to change Your rules (or deactivate it) ?
![2018_04_13_15_19_56_rules](https://user-images.githubusercontent.com/23656259/38737854-cb1d6594-3f30-11e8-8143-d8dc83625cad.png)

![2018-04-13 15_18_34-rules](https://user-images.githubusercontent.com/23656259/38737861-d0ce27da-3f30-11e8-8e1e-0639b5617caf.png)

**Comment by racodond** [comment]
Hi,

This is not related to the CSS plugin but to SonarQube itself. Built-in profiles cannot be modified. If you want to create your own CSS quality profile, copy the built-in profile and then activate/deactivate rules at your will.

Regards,

David
