### ISSUE TITLE
user-select css property

### ISSUE THREAD

**Issue by ARMANDVDM** [racodond/sonar-css-plugin#101]
Hi There,

I would like to find out if its possible to review the experimental status on the **user-select** property in css. This property is now supported by all modern browsers, of course with the exception of some mobile browsers, however in my mind this shouldn't matter all that much since there is no real use for the **user-select** property in these browsers anyway. Well at least not for **user-select: none**.

I would much rather see if this is something that can be updated on your side rather than having to use an inline style to bypass this issue I am facing and definitely not going to switch off the blanket rule for all these properties either. 

Any feedback will be appreciated and keep up the good work!

Best Regards
Armand

**Comment by racodond** [comment]
Hi Armand,

It doesn't seem to be fully supported by all browsers without vendor prefix (Firefox for instance). Thus, I'd like to keep it as 'experimental' for now.

I already thought about it and it could be the right time to implement it. I can add a custom parameter to the rule that would allow some properties to no longer be considered as experimental. Would that answer your need?

Thank you

Regards,

David

**Comment by ARMANDVDM** [comment]
Hi David,

Thanks for the response. A custom parameter will surely do the trick. If we're able to define our own exceptions without switching off an entire blanket rule then that would bring a whole lot of flexibility to our development cycles. For example, we had to switch off a whole lot of stuff the other day for the placeholder pseudo class as well since our client was very particular on the colour of the placeholder text in our app and quite frankly that makes me very nervous :) 

Thanks for your feedback and looking forward to your reponse.

Best Regards
Armand

**Comment by racodond** [comment]
Hi Armand,

> A custom parameter will surely do the trick. If we're able to define our own exceptions without switching off an entire blanket rule then that would bring a whole lot of flexibility to our development cycles.

OK. Issue created: https://github.com/racodond/sonar-css-plugin/issues/102


> For example, we had to switch off a whole lot of stuff the other day for the placeholder pseudo class as well since our client was very particular on the colour of the placeholder text in our app and quite frankly that makes me very nervous :)

Can you tell me a bit more to see if we can do something about it?

Regards,

David

**Comment by ARMANDVDM** [comment]
Hi David,

Thanks for this. 

With regards to your question, we had to switch off the whole "**scss:experimental-pseudo-usage**" rule to change the colour of the placeholder text meaning that Sonar would now accept all of the other experimental pseudos like `any-link`, `backdrop`, `blank`, `content `etc. The only ones that we would possibly want to use out of that entire rule at a glance would be `has `and `placeholder`. I believe if we had the ability to switch off Sonar checking on certain experimental properties and pseudo classes as opposed to allowing all of it to slip through by switching off the entire rule then that will be very useful.

I hope this answers your question.

Thanks again & Best Regards
Armand

**Comment by racodond** [comment]
Hi Armand,

I extended https://github.com/racodond/sonar-css-plugin/issues/102 to target properties, pseudo elements, functions and @-rules.

Regards,

David

**Comment by ARMANDVDM** [comment]
Hi David,

Thanks for this.

Best Regards
Armand

**Comment by racodond** [comment]
Here's a snapshot that adds a parameter to the experimental-property-usage rule: https://github.com/racodond/sonar-css-plugin/releases/tag/fix102. Tell me if it suits your needs. If so, I'll extend the rule to functions, at-rules, pseudo-elements.

**Comment by ARMANDVDM** [comment]
Hi David,

We have implemented your change and it works fantastically well.
I think its safe to say that you may proceed to extend this rule to the functions, at-rules and pseudo-elements.

Many thanks!

Regards
Armand

**Comment by racodond** [comment]
Thanks for your feedback!
I just released a new version with this enhancement: https://github.com/racodond/sonar-css-plugin/releases/tag/4.16
