### ISSUE TITLE
Support CSS Fonts Module Level 4

### ISSUE THREAD

**Issue by pats** [racodond/sonar-css-plugin#105]
Hi,

Would be nice to have a support for font-display property. Currently plugin caused error:

Remove this usage of the unknown "font-display" property.

Regards,
PS

**Comment by racodond** [comment]
Hi @pats,

Thanks for your feedback!

I'll add support for the missing properties/descriptiors in https://drafts.csswg.org/css-fonts-4:
- font-display
- font-min-size
- font-max-size
- font-variation-settings
- font-optical-sizing
- base-palette
- font-variant-emoji 

And the @-rule: @font-palette-values

Regards,

David

**Comment by racodond** [comment]
Released in https://github.com/racodond/sonar-css-plugin/releases/tag/4.17
