### ISSUE TITLE
`MissingNewLineAtEndOfFileCheck` should skip empty files

### ISSUE THREAD

**Issue by axelboc** [racodond/sonar-css-plugin#107]
Stylelint's corresponding rule, [`no-missing-end-of-source-newline`](https://stylelint.io/user-guide/rules/no-missing-end-of-source-newline/), does skip empty files. Adding a line break in an empty file to fix the warning in Sonar seems ... smellier. 😄

**Comment by racodond** [comment]
Hi @axelboc,

Thanks for your feedback! I fully agree with you and I'll fix it right away.

Regards,

**Comment by axelboc** [comment]
Awesome, thanks!

**Comment by racodond** [comment]
Released in 4.18: https://github.com/racodond/sonar-css-plugin/releases/tag/4.18
