### ISSUE TITLE
Unknown type selectors - exclusion

### ISSUE THREAD

**Issue by QADEvops1** [racodond/sonar-css-plugin#109]
Hello,

I have updated CSS / SCSS / Less to 4.17
Here I wanted to exclude some keywords

I tried this by updating the SCSS quality profile.
(?i)abc\-

My code has something like this
abc-search
{
}

It is not ignoring this keyword and shows an issue (SCSS).
Please let me know if I am doing something wrong here.

**Comment by racodond** [comment]
Hello @QADEvops1,

The regular expression should be `(?i)abc-.+`.
For your information, I updated the documentation of the parameter: https://github.com/racodond/sonar-css-plugin/commit/dd894460752cb0c473f8387f04158d6b50ceb673

Regards,

David

**Comment by QADEvops1** [comment]
Thanks David, it worked.

How can I exclude multiple items, say I have
abc-
def-

**Comment by racodond** [comment]
Cool!

(?i)(abc|def)-.+)
