### ISSUE TITLE
Parsing nested lesscss declarations can reach to false positive critical issues in sonarqube

### ISSUE THREAD

**Issue by LudoMeurillon** [racodond/sonar-css-plugin#11]
Hello,

I'm facing a lot of "false positive" alerts on a big less codebase with SonarQube CSS plugin.

Most of thos "false positive" seems linked to nested declarations in lesscss

for example, when parsing a nested rule like

    .mySubClass {
        background-color: blue;

        html:not(.myClass) & {
            ...
        }
    }

it leads to 2 differents alerts that should not be thrown

- **Unknown properties should be removed** -> Remove this usage of the unknown "html" property.
- **Unknown CSS / Less functions should be removed** -> Remove this usage of the unknown "not" function.

it seems that `html:not(...)` is parsed as if it was a css property and not a nested rule.

**Comment by kingoleg** [comment]
Please check the latest version https://github.com/racodond/sonar-css-plugin/releases/tag/4.2. It was released to handle this issue.

**Comment by LudoMeurillon** [comment]
Oh great, I'll try it as soon as possible.

Do you known why I'm not seeing this plugin version in the update center ? I'm using SonarQube 6.3.1 and only 3.1 plugin version is referenced in the plugin version matrix : 

https://docs.sonarqube.org/display/PLUG/Plugin+Version+Matrix

**Comment by LudoMeurillon** [comment]
By the way, the new 4.2 release works fine and fix the bug, thank you

**Comment by racodond** [comment]
Hi @LudoMeurillon,

> By the way, the new 4.2 release works fine and fix the bug, thank you

Cool! Thanks for the feedback.

> Do you known why I'm not seeing this plugin version in the update center ? I'm using SonarQube 6.3.1 and only 3.1 plugin version is referenced in the plugin version matrix

I don't like how SonarSource deal with community work and contributors. That's why I no longer contribute my work (CSS, JSON, Gherkin, Java Properties plugin) to the Update Center.

David
