### ISSUE TITLE
Please add support for Angular Material

### ISSUE THREAD

**Issue by Azemsha** [racodond/sonar-css-plugin#112]
BUG: Remove this usage of the unknown **"mat-icon"** type selector.

Please add support for the [Angular Material of the new version](https://material.angular.io/)

**Comment by racodond** [comment]
Hi @Azemsha,

Which version of the plugin are you running?
Because, for several versions, the rule can be parametrized to exclude some prefixes.

David

**Comment by Azemsha** [comment]
@racodond 
We use a plugin with version 4.18.
I think that support for the new version of Angular Matertial will only benefit. Thank you

**Comment by racodond** [comment]
First, does it work with the parameter?
Then, I'll see.
