### ISSUE TITLE
How to flag some pseudo elements as non-experimental?

### ISSUE THREAD

**Issue by glucazeau** [racodond/sonar-css-plugin#113]
I've seen that from version 4.16 thanks to this issue #102 we can now exclude some elements from the "experimental" list.
How do you populate the "propertiesToExclude" parameter? I tried looking for documentation but couldn't find anything, and all my attempts to set it from the sonar-project.properties failed.

Thank you for the help :)

**Comment by racodond** [comment]
Hi @glucazeau,

It's done directly at rule level in your quality profile.

![image](https://user-images.githubusercontent.com/1215713/40771274-35bbf4fe-64bd-11e8-9088-7771843e2970.png)

Note that only custom quality profiles can be updated (not the built-in one).

David

**Comment by glucazeau** [comment]
Thank you David :)
