### ISSUE TITLE
NPE on rule box-model

### ISSUE THREAD

**Issue by racodond** [racodond/sonar-css-plugin#115]
See http://stackoverflow.com/questions/41889352/failed-analysis-for-scss-file

**Comment by racodond** [comment]
A snapshot is available at https://github.com/racodond/sonar-css-plugin/releases/tag/115

**Comment by alixwar** [comment]
A second analysis (with 3.0) and the same code base does not trigger the nullpointer for some reason

**Comment by racodond** [comment]
With version 3.0, the issue can be raised or not depending on which order files are analyzed. If the first file analyzed contains a ruleset before any mixins, it'll succeed, if not, it'll crash. As files are analyzed randomly, the issue will likely reappear again. If you just run the analysis on one single file containing the piece of code you provided, the analysis should always crash.

Note also that with version 3.0, even if the analysis doesn't crash, it'll produce some false positives.
