### ISSUE TITLE
Cannot enable both this plugin and the built-in "SonarCSS" plugin

### ISSUE THREAD

**Issue by MaxTranced** [racodond/sonar-css-plugin#115]
If both plugins are enabled, analysis fails with this exception:

    java.lang.IllegalArgumentException: Multiple entries with same key: css=CSS and css=CSS
	at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:150)

According to the answer here https://stackoverflow.com/a/35362984/ this can be avoided.

Please change the plugin so that both can be active at the same time. Thank you!

**Comment by racodond** [comment]
Hi @MaxTranced,

SonarSource purposedly took the same key as my CSS plugin.
I don't want to maintain my CSS plugin anymore. Feel free to fork this repository if you want to update it.

Thanks for your understanding

David

**Comment by MaxTranced** [comment]
@racodond Thank you for the quick answer!
