### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by rafaelmaiach** [racodond/sonar-css-plugin#116]
Hi, I installed sonar-css-plugin on a local SonarQube Server. I'm trying to set CSS naming convention to BEM convention (^(_)?[a-z]+-[a-z0-9-]+((_{2}|-{2})?[a-z0-9-]+)?(-{2}[a-z0-9-]+)?[a-z0-9]$) but I cannot find where I do this. I try search on google and sonarqube interface, but I didn't find. Where I do this? And how can I disable rules like "leading zero" ?

Thank you

**Comment by racodond** [comment]
Hi @rafaelmaiach,

Built-in profiles cannot be updated. If you want to make some changes on the set of rules that are activated, copy the built-in profile, make it the default one and activate/deactivate rules and update configuration of some rules.

See https://docs.sonarqube.org/display/SONAR/Quality+Profiles for more details.

David

**Comment by rafaelmaiach** [comment]
Hi @racodond 
Thank you so much. I did that and it worked! The interface was not intuitive to me to think about make a copy and use that.
