### ISSUE TITLE
Add support for SCSS

### ISSUE THREAD

**Issue by pascalberger** [racodond/sonar-css-plugin#12]
Support for checking [Sass](http://sass-lang.com/) (especially the SCSS syntax) would be a nice addition.

Here's [a Styleguide](https://sass-guidelin.es/) which can be a good base for rules to be implemented.

**Comment by slavonnet** [comment]
+1

**Comment by OnekO** [comment]
Waiting for it!

**Comment by racodond** [comment]
@OnekO :-) I'll try to start working on it as soon as I can

**Comment by OnekO** [comment]
Nice to hear it, good luck and thanks for all the work!

**Comment by racodond** [comment]
Work on this issue will be pushed to https://github.com/racodond/sonar-css-plugin/tree/feature/12
