### ISSUE TITLE
Rule validate-property-value: Update ‘animation’ validator to support multiple animations

### ISSUE THREAD

**Issue by walthhy** [racodond/sonar-css-plugin#13]
Hi,

2 issues:
a. Seems animation checking rule does not accept second "single-animation"
b. Rule output does not align with animation definitions

plugin rule output: 
Update the invalid value of property "animation". Expected format: <time> || <single-timing-function> || <time> || <single-animation-iteration-count> || <single-animation-direction> || <single-animation-fill-mode> || <single-animation-play-state> || <single-animation-name>

Refer to following link http://www.w3.org/TR/css3-animations/#animations
animation <single-animation> [ ‘,’ <single-animation> ]* 
<single-animation> = <single-animation-name> || <time> || <single-animation-timing-function> || <time> || <single-animation-iteration-count> || <single-animation-direction> || <single-animation-fill-mode> || <single-animation-play-state>

Example: it will fire css:validate-property-value. however there is no rule fired if second single animation is removed.
.alert.show {
    visibility: visible;
    animation: fadein .5s, fadeout 1s;
}
@keyframes fadein {
    from { opacity: 0;}
    to { opacity: 1;}
}
@keyframes fadeout {
    from { opacity: 1;}
    to { opacity: 0;}
}

**Comment by racodond** [comment]
Hi @walthhy,

Thanks for your feedback!
You're right, it should support multiple single animations.

David
