### ISSUE TITLE
Accept 8 digit color and 4 digit color

### ISSUE THREAD

**Issue by kingoleg** [racodond/sonar-css-plugin#17]
According to https://drafts.csswg.org/css-color/#typedef-hex-color, color can be 8 digits length:

> The first 6 digits are interpreted identically to the 6-digit notation. The last pair of digits, interpreted as a hexadecimal number, specifies the alpha channel of the color, where 00 represents a fully transparent color and ff represent a fully opaque color. 

But currently I get "Update the invalid value of property "color". Expected format: < color >" for  `color: #acacacac;`

**Comment by racodond** [comment]
Thanks @kingoleg for your feedback!
