### ISSUE TITLE
Update validators for properties 'justify-content' and 'align-content'

### ISSUE THREAD

**Issue by kingoleg** [racodond/sonar-css-plugin#18]
According to https://drafts.csswg.org/css-align-3/#typedef-content-position  justify-content can be  left or right

> 
> < content-position >
>     This set is used by justify-content and align-content to align the box’s contents within itself.
> 
>     < content-position > = center | start | end | flex-start | flex-end | left | right;

But currently I get "Update the invalid value of property "justify-content". Expected format: flex-start | flex-end | center | space-between | space-around" for `justify-content: left;`

**Comment by racodond** [comment]
Thanks for your feedback @kingoleg!
Validator is based on https://drafts.csswg.org/css-flexbox-1/#propdef-justify-content for now.
https://drafts.csswg.org/css-align-3/#typedef-content-position is a bit more complex... I'll work on it.
