### ISSUE TITLE
Add support of /deep/ selector combinator

### ISSUE THREAD

**Issue by Bbbrinks** [racodond/sonar-css-plugin#2]
I'm getting parse errors on .scss files that contain a /deep/ selector.

Code:
`/deep/ .modal-content { ^ 17: width: $sp-modal-small-width; 18: }`

Error:

> Parse error at line 16 column 1: 6: top:20px; 7: right:20px; 8: color: $gray-light; 9: opacity: 1; 10: } 11: 12: .close:focus, .close:hover { 13: opacity: 0.75; 14: } 15: 16: /deep/ .modal-content { ^ 17: width: $sp-modal-small-width; 18: } 19: 20: .modal-header { 21: padding: 0px $sp-modal-side-padding; 22: height: $sp-modal-header-height; 23: } 24: 25: .modal-body { 26: padding: $sp-modal-content-vertical-padding $sp-modal-side-padding

I think this is a bug in the sonar-scanner but I can't find any references to it anywhere online.

So i guess this is a bug report.

Cheers,

Bob

**Comment by racodond** [comment]
Hi Bob,

As far as I understand, /deep/ is deprecated and has never been supported by all main vendors, right? If so, can you get rid off it?

Thanks

David

**Comment by Bbbrinks** [comment]
Hi David,

Angular 2 supports the /deep/ selector in emulated view encapsulation.

> Use the /deep/ and >>> selectors only with emulated view encapsulation. Emulated is the default and most commonly used view encapsulation. For more information, see the Controlling view encapsulation section.
(https://angular.io/docs/ts/latest/guide/component-styles.html) 

Or did they not update their documentation?

I only use /deep/ in combination with angular 2 and it seems to work fine in recent browsers. And removing it in my project would be non-trivial.

Bob

**Comment by racodond** [comment]
Thanks for the link to Angular! I'm off for two weeks but I'll work on a fix when I get back.

**Comment by Bbbrinks** [comment]
Thanks, I tried to fork and fix it myself but I know nothing about sonarqube plugins so I couldn't get it to work.

**Comment by racodond** [comment]
See also https://www.w3.org/TR/css-scoping-1/#deep-combinator

**Comment by racodond** [comment]
Update rule `experimental-selector-combinator-usage` by adding this deep selector combinator.

**Comment by HiperSoke** [comment]
I'm using version 4.7 and this is still not working
`Parse error at line 44 column 1: 34: border-color: #8cd1fa; 35: border-radius: 5px; 36: border-style: solid; 37: border-width: 1.5px; 38: height: 35px; 39: margin-bottom: 10px; 40: text-align: left; 41: width: 70px; 42: } 43: 44: /deep/ .btngroupstyle { ^ 45: background-color: #ffffff; 46: border-color: #8cd1fa; 47: border-style: solid; 48: border-width: 1.5px; 49: height: 35px; 50: } 51: 52: .buttonload { 53: background-color: #0098f3; 54: color: #ffffff;`

The css that i'm using looks like this:
`/deep/ .btngroupstyle {
    background-color: black;
    border-color: #8cd1fa;
}`

Regards.
