### ISSUE TITLE
filter: progid:DXImageTransform.Microsoft.gradient(enabled = false); Maybe additional rule with recomendation to migration?

### ISSUE THREAD

**Issue by slavonnet** [racodond/sonar-css-plugin#20]
`
  filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);
`
Result - Update the invalid value of property "filter". Expected format: none | [<uri> | <filter-function>]
Q: This common useage for "old style". Maybe additional rule with recomendation to migration?

**Comment by racodond** [comment]
There's another rule (css:obsolete-functions) stating that this Microsoft gradient function is deprecated:

![image](https://cloud.githubusercontent.com/assets/1215713/18738900/0dc54426-80a0-11e6-848d-17fde96856d0.png)

The description of this rule links to the Microsoft documentation stating that this function is deprecated. Then, it is up to the developer to make a quick search to learn how to update the code. If you find a nice link about how to update the code in this case, I'll add it to the rule description.

This is related to https://github.com/racodond/sonar-css-plugin/issues/3

Note that it requires version 2.2 of the CSS plugin (not yet released). You can build it from the master branch.
