### ISSUE TITLE
Non standard for WebKit word-break: break-word;

### ISSUE THREAD

**Issue by kingoleg** [racodond/sonar-css-plugin#20]
According to https://css-tricks.com/almanac/properties/w/word-break/ `word-break: break-word;` is a non standard for WebKit value

Currently the plugin mark it as critical issue "Update the invalid value of property "word-break". Expected format: normal | keep-all | break-all" for `word-break: break-word;`

I assume it should be normal issue or something.

**Comment by racodond** [comment]
There's one single rule validating all properties. Thus the default severity (critical in this case) is the same for all issues whatever the property. You can either update the default severity of the rule in your quality profile or change the severity for this very specific issue (https://docs.sonarqube.org/display/SONAR/Issues) or flag this issue as Won't fix.
