### ISSUE TITLE
Update background-position validator (multiple backgrounds)

### ISSUE THREAD

**Issue by adbutterfield** [racodond/sonar-css-plugin#25]
Hi!

I have some rules in a class, kind of like this:

    background-image: url("/pic1.png"), url("/pic2.png");
    background-position: center center, top left;

It got flagged as as an error:
Update the invalid value of property "background-position". Expected format: [ <length> | <percentage> | top | bottom | center | left | right ]+

I was following this page on MDN to implement the multiple background images:
https://developer.mozilla.org/en/docs/Web/CSS/CSS_Background_and_Borders/Using_CSS_multiple_backgrounds

I'm guessing the rule isn't handling multiple values for background-position correctly?

**Comment by racodond** [comment]
Hi @adbutterfield,

Thanks for your feedback! I'll upgrade the validator to CSS Backgrounds and Borders Module Level 3: https://drafts.csswg.org/css-backgrounds-3/#bg-position

David
