### ISSUE TITLE
Version 4.0 or higher not available in update center

### ISSUE THREAD

**Issue by rodikal** [racodond/sonar-css-plugin#26]
Hi,

The latest version of the plugin we see in the update center is version 3.1 . Versions 4.0 to 4.4 are not available. Will they become available or should we install them manually? And what about the compatibility with different SonarQube versions?

**Comment by racodond** [comment]
Hi @rodikal,

> The latest version of the plugin we see in the update center is version 3.1 . Versions 4.0 to 4.4 are not available. Will they become available or should we install them manually?

I update the README file to not mention the Update Center anymore. This repo is no longer the "official" repo available in the SonarQube Update Center as I decided to step out of the community led by SonarSource. Thus, you will have to manually install those versions.

> And what about the compatibility with different SonarQube versions?
Good point! I updated the release notes of version 4.4 to state the compatibility with SonarQube 5.6+.
I'll add the compatibility for any future releases.

David
