### ISSUE TITLE
nth-of-type selector problem in less scan

### ISSUE THREAD

**Issue by lukaszun** [racodond/sonar-css-plugin#27]
Sonar rises issues with following less snippet:

`span:nth-of-type(2) {
            width: 4.6%;
            display: inline-block;
            text-align: center;
          }`

Theses issues are:
- Remove this usage of the unknown "span" property. 
- Remove this usage of the unknown "nth-of-type" function.
- Add a semicolon at the end of this declaration
- Add one whitespace between the colon and the value

Thats wrong as less code is correct.

**Comment by racodond** [comment]
Hi @lukaszun,

It looks like a duplicate of https://github.com/racodond/sonar-css-plugin/issues/3.
Could you please give a try to the latest version: https://github.com/racodond/sonar-css-plugin/releases/tag/4.4 ?

Thanks

David

**Comment by lukaszun** [comment]
Hi @racodond ,

I can't see it available via Sonar Qube's update center. Shall I install it manually?

**Comment by racodond** [comment]
Hi @lukaszun,

This repo is no longer available through SonarQube Update Center. See https://github.com/racodond/sonar-css-plugin/issues/26 for more details. Thus, you'll have to install it manually.

David

**Comment by lukaszun** [comment]
After upgrading to version 4.4 problem is solved.
