### ISSUE TITLE
:not selector problem in less scan

### ISSUE THREAD

**Issue by lukaszun** [racodond/sonar-css-plugin#28]
Hi @racodond ,
I'm using version 4.4 of plugin. Sonar rises issue with following less snippet:

`tr:not(.big-container) > {
      width: 100px;
    }`

Theese issues are:
- Remove this usage of the unknown "tr" property.
- Remove this usage of the unknown "not" function.

**Comment by racodond** [comment]
Hi @lukaszun,

Thanks for your feedback!
I'm not really expert in Less... Could you please tell me the purpose of this syntax? Compared to
```
tr:not(.big-container) { width: 100px; }
```
Could you also point me to some documentation detailing this syntax?

Thank you

David

**Comment by lukaszun** [comment]
Hi @racodond,
:not(selector) syntax means every element without given selector. Please check this out for details: https://developer.mozilla.org/pl/docs/Web/CSS/:not

Best regards,
Luke

**Comment by racodond** [comment]
My question was about the selector combinator `>`. What is it for here? It combines the `tr:not()` selector with no selector... I cannot find any documentation stating that this syntax is correct (even if the Less parser seems to handle it by just ignoring the combinator and removing it). Thus, my questions are:
* Can you just remove this 'useless' combinator?
* Can you find any documentation about combining with nothing in Less or it is just a corner case / wrong syntax that is luckily handled by the Less parser?

**Comment by lukaszun** [comment]
You are right, my mistake... Thanks @racodond.

**Comment by vaclav-dvorak** [comment]
Hello the ">" does not seem the main problem here... at least not for us.

We have completely same false positives for line like this:
li:not(.slim) {
 max-width: 60px;
}

- Remove this usage of the unknown "li" property.
- Remove this usage of the unknown "not" function.
- Add a semicolon at the end of this declaration.

**Comment by racodond** [comment]
@vaclav-dvorak I don't reproduce the issue with your code sample. Which version of the plugin are you running?

**Comment by vaclav-dvorak** [comment]
@racodond i was taken here from sonar update centre but i figured out that we actually have different plugin with same name installed  from https://github.com/kalidasya/sonar-css-plugin.

got confused as hell by it :D we will try your plugin it seems more updated.
Sorry for possibly false positive report :(

**Comment by racodond** [comment]
No problem @vaclav-dvorak :-)
See https://github.com/racodond/sonar-css-plugin/issues/24
