### ISSUE TITLE
Erroneous STATEMENT_BLOCK recognition order for Less

### ISSUE THREAD

**Issue by kingoleg** [racodond/sonar-css-plugin#3]
Hi,

I have a less file with next code:

```less
.documents-table {
    th:nth-child(1), td:nth-child(1) {
...
```

And sonar-css-plugin create 4 violations on it:

1. Add one whitespace between the colon and the value. - but it's not a value for :, it's a pseudo class
2. Add a semicolon at the end of this declaration. - But it's not the end of the declaration
3. Remove this usage of the unknown "th" property. - But his is not a property, this is child less selector tag
4. Remove this usage of the unknown "nth-child" function.  - But this is well-known pseudo class, not a function

I am using 3.1 version of plugin.

**Comment by racodond** [comment]
Hi @kingoleg,

I'm off for two weeks. Could you please confirm that you face the same issue with version 4.0? If so, I'll have a look when I come back.

David

**Comment by julkuh** [comment]
Hey,
i can reproduce this issue with **4.1** release

**Comment by racodond** [comment]
STATEMENT_BLOCK recognition order should be:

LESS_VARIABLE_DECLARATION(),
AT_RULE(),
RULESET(),
CSS_DECLARATION(),
LESS_MIXIN_CALL(),
EMPTY_STATEMENT()

instead of

DECLARATION(),
AT_RULE(),
RULESET(),
LESS_MIXIN_CALL(),
EMPTY_STATEMENT()

**Comment by racodond** [comment]
@kingoleg @julkuh: Version 4.2 should fix your issues: https://github.com/racodond/sonar-css-plugin/releases/tag/4.2

**Comment by kingoleg** [comment]
@racodond thanks, I will check next week

**Comment by kingoleg** [comment]
@racodond Checked in last version. Looks like it works. Thanks

**Comment by racodond** [comment]
@kingoleg Cool! Thanks for the feedback!
