### ISSUE TITLE
Rule scss:experimental-property-usage flags supported rules

### ISSUE THREAD

**Issue by hcomnetworkers** [racodond/sonar-css-plugin#30]
The rule "Experimental properties should not be used" flags properties like `text-overflow: ellipsis;` which are supported by all current browsers for a long time.
(http://caniuse.com/#search=text-overflow)

Could you please exclude those properties from the rule, which are broadly supported? Or maybe split up the rule by pure-experimental and experimental-but-supported?

Thank you

**Comment by racodond** [comment]
Hi @hcomnetworkers,

It's been fixed in version 4.3. What version are you running?

Thanks

David

**Comment by marciomsm** [comment]
Similar error: "Remove this usage of the experimental "box-shadow" property."

`box-shadow: none;`

Is it on the same fix?

Thanks.

**Comment by racodond** [comment]
Hi @marciomsm,

It has even been fixed before: https://github.com/racodond/sonar-css-plugin/commit/d013dcde1d421353718c3a87d48bfb8fde46bfa2

Just upgrade to the latest version (4.5).

David

**Comment by marciomsm** [comment]
@racodond thank you.

I updated to the latest version and the bug was fixed.

**Comment by hcomnetworkers** [comment]
@racodond thanks for your response.

We are using the 3.1 Version which is the latest version in the Sonar Update Center. Is there any chance that the 4.x Versions will be available through the Update Center?

**Comment by racodond** [comment]
@hcomnetworkers You're welcome!
There's zero chance that 4.x versions will be available through the Update Center. See https://github.com/racodond/sonar-css-plugin/issues/24
