### ISSUE TITLE
Less Parser error: mixin parameter does not accept expression

### ISSUE THREAD

**Issue by vaclav-dvorak** [racodond/sonar-css-plugin#31]
Hello we encountered this failure in less parser however lessc compile this normally

`.sprites(@sprites, @i: 1) when (@i <= length(@sprites)) {`
`  @sprite: extract(@sprites, @i);`
`  @sprite-name: e(extract(@sprite, 10));`
`  .@{sprite-name} {`
`    .sprite(@sprite);`
`  }`
`  .sprites(@sprites, @i + 1);`
`}`

Parse error at line 569 column 25: 
567: .sprite(@sprite);
568: }
569: .sprites(@sprites, @i + 1); ^
570: }

We don't see anything wrong with it. We are using version 4.5. Can you advice?

**Comment by racodond** [comment]
Hi @vaclav-dvorak,

Thanks for your feedback!
I can reproduce the issue.

David

**Comment by racodond** [comment]
Fix grammar around `LESS_MIXIN_PARAMETER`. Should accept expression. See `SCSS_SASS_SCRIPT_EXPRESSION_WITHOUT_COMMA_SEPARATED_LIST`
