### ISSUE TITLE
Less Parser error: 'not' only supported for first mixin guard condition

### ISSUE THREAD

**Issue by vaclav-dvorak** [racodond/sonar-css-plugin#32]
Hello we encountered this failure in less parser however lessc compile this normally

`// Set the background opacity with no opaque on content`
`.background-opacity(@c, @alpha) when (iscolor(@c)) and not (@c=~"transparent") {`
`    background: hsla(hue(@c), saturation(@c), lightness(@c), @alpha);`
`}`

Parse error at line 11 column 63:
10: // Set the background opacity with no opaque on content
11: .background-opacity(@c, @alpha) when (iscolor(@c)) and not (@c=~"transparent") { ^ 
12: background: hsla(hue(@c), saturation(@c), lightness(@c), @alpha); 
13: }

We don't see anything wrong with it. We are using version 4.5. Can you advice?

**Comment by racodond** [comment]
Hi @vaclav-dvorak,

Thanks for your feedback!
I can reproduce the issue.

David

**Comment by racodond** [comment]
Fix grammar around `LESS_MIXIN_GUARD` and `LESS_MIXIN_GUARD_CONDITION_LIST` to accept `and` and `or` followed by `not`.
