### ISSUE TITLE
Analyze CSS in HTML, XHTML, etc. files

### ISSUE THREAD

**Issue by racodond** [racodond/sonar-css-plugin#33]
Analyze CSS code between `<script type="text/css">...</script>` tags.

**Comment by kalidasya** [comment]
@racodond should not this contain when css is inside `<style>` tags? or I might got something wrong... and its a shame github does not let you to seach in this repo because its forked.

**Comment by racodond** [comment]
Hi @kalidasya,

Thanks a ton for your feedback! You're absolutely right.
I guess I was tired to make such a mistake...

David

**Comment by kalidasya** [comment]
@racodond cool, really nice improvements btw, I am sorry I dont work on any css/html projects anymore

**Comment by racodond** [comment]
It should now be fixed. Thanks again!

> cool, really nice improvements btw

Thanks!

>  I am sorry I dont work on any css/html projects anymore

Too bad for you ;-)
