### ISSUE TITLE
FP on rule display-property-grouping with float:none

### ISSUE THREAD

**Issue by Chevskis** [racodond/sonar-css-plugin#40]
Hi,

We have encountered reporting of major issues which are false positives in some cases because of the following rule:
> Remove this "float" declaration that does not work with the "display" declaration.

This should be the case in scenarios like:
`
display: inline-block;
float: left;
`

But the issue is reported also when float is disabled because it is not supposed to be used with floats:
`
display: inline-block;
float: none;
`

**Comment by racodond** [comment]
Hi @Chevskis,

Thanks for your feedback!
I'll fix this false positive in the next version.

David
