### ISSUE TITLE
scss:unknown-type-selector: Add support for custom elements

### ISSUE THREAD

**Issue by fxOne** [racodond/sonar-css-plugin#41]
Can you please add support for custom elements as i get currently the following issue: `Remove this usage of the unknown "my-custom-element" type selector.`

It would be great if I could add a regex to match my components.

**Comment by racodond** [comment]
Hi @fxOne,

Thanks for your feedback!

I had this discussion while implementing https://github.com/racodond/sonar-css-plugin/issues/35 with the reporter of the issue. I decided to implement it when somebody would come with such a need. So, I'll implement it in next version.

For my information, could you please tell a bit more about those custom elements? Context? Lib/Framework?

Thanks!

David
