### ISSUE TITLE
FP on rule 'Units for zero length values should be removed' on keyframes selector

### ISSUE THREAD

**Issue by thanhnhan2tn** [racodond/sonar-css-plugin#43]
Should not check `Units for zero length values should be removed` in keyframes 0%
http://www.w3schools.com/cssref/css3_pr_animation-keyframes.asp

**Comment by racodond** [comment]
@thanhnhan2tn Thanks a lot for reporting this false positive!

**Comment by racodond** [comment]
```
@keyframes mymove {
  0%   {top: 0;}                 /* Should not raise an issue on 0% */
  25%  {top: 200px;}
  50%  {top: 100px;}
  75%  {top: 200px;}
  100% {top: 0;}
}
```

**Comment by racodond** [comment]
@thanhnhan2tn Here's a snapshot embedding the fix: https://github.com/racodond/sonar-css-plugin/releases/tag/%2343-%2344. Feel free to test it and provide some feedback.

**Comment by thanhnhan2tn** [comment]
Thank you, I will update this version and tell you if any problem.
