### ISSUE TITLE
Parsing errors

### ISSUE THREAD

**Issue by Fischermaen** [racodond/sonar-css-plugin#5]
Hi,

for every less file encoding with UTF-8 *with* BOM I get an parsing error. (less:S2260) What can I do?

Kind Regards
Andy

**Comment by racodond** [comment]
Hi Andy,

Files with BOM are supposed to be supported by the plugin. Did you set the sonar.sourceEncoding property to UTF-8?

David

**Comment by Fischermaen** [comment]
Hi David,

the source encoding of SonarEncoding is set to UTF-8. We have a project where some less-files are encoded UTF-8 with BOM and some UTF-without BOM. And only those files encoded in UTF-8 with BOM are reporting that issue. We are using the latest version of plugin (4.0)

Kind regards 
Andy

**Comment by racodond** [comment]
OK. Could you please provide one of those files with BOM?

**Comment by Fischermaen** [comment]
I will send you one of these files as soon as I'm back to office tomorrow.

**Comment by Fischermaen** [comment]
I have attached two samples, one less and one json file reporting that error

[Source.zip](https://github.com/racodond/sonar-css-plugin/files/954791/Source.zip)

**Comment by racodond** [comment]
Thanks! I'll have a look at them when I get back home beginning of next week.

**Comment by racodond** [comment]
Setting the encoding to UTF-8 through the `sonar.sourceEncoding` property makes the analysis succeeds on my side. Could you run an analysis with the following project and tell me how it goes?
[testcss.zip](https://github.com/racodond/sonar-css-plugin/files/973161/testcss.zip)

If it fails, could you please provide the log of the analysis?

Thanks

**Comment by Fischermaen** [comment]
Hi David,

I ran the test and now it passes. I get an "Remove BOM" issue for each file. No I'll take a look at the configurations of the projects raising the parsing errors.

Thank you for your help!

Kind regards
Andy

**Comment by racodond** [comment]
Good news!
