### ISSUE TITLE
Remove 'fill' from the experimental property list.

### ISSUE THREAD

**Issue by sebsnake** [racodond/sonar-css-plugin#51]
I would recommend removing 'fill' from the list of 'experimental properties'.
As the rule "Experimental properties should not be used" states:

> A property is considered as experimental if it is not supported by IE/Edge 11+, Firefox 44+ and Chrome 48+. 

As far as I can see, 'fill' is supported by all of these browsers, down to IE 9+ ([source](https://css-tricks.com/almanac/properties/f/fill/#browser-support)).

**Comment by racodond** [comment]
Hi @sebsnake,

Thanks for your feedback!

I agree with you. Moreover, all properties listed in SVG specifications version 1.1 (https://www.w3.org/TR/2003/REC-SVG11-20030114/propidx.html) should be marked as supported.

David
