### ISSUE TITLE
Is there any stylelint file with the same configuration as this plugin?

### ISSUE THREAD

**Issue by marciomsm** [racodond/sonar-css-plugin#55]
Is there any stylelint file with the same configuration as this plugin? Something that I can use in my IDE (VS Code) to get the errors during the development.

Thanks.

**Comment by racodond** [comment]
Hi @marciomsm,

No there's no stylelint file provided with the plugin as everyone can define their own set of SonarQube rules to check. But you can build your own stylelint file with the help of the stylelint/SonarQube rule mapping: https://github.com/racodond/sonar-css-plugin/blob/master/doc/stylelint-sonarqube-rule-mapping.md

Cheers,

David
