### ISSUE TITLE
ClassSelectorNamingConventionCheck negative regex support

### ISSUE THREAD

**Issue by roookeee** [racodond/sonar-css-plugin#58]
Would it be possible to extend the ClassSelectorNamingConventionCheck.java to include a regex which a classname should not match?

**Comment by racodond** [comment]
Hi @naze,

Can't you write such a regex? See for example https://stackoverflow.com/questions/2637675/how-to-negate-the-whole-regex

Cheers,

David

**Comment by racodond** [comment]
Hi @naze,

I'm closing this issue. Feel free to reopen it if you have any more question about it.

David
