### ISSUE TITLE
Add support for Less

### ISSUE THREAD

**Issue by racodond** [racodond/sonar-css-plugin#6]
See http://lesscss.org/

**Comment by pascalberger** [comment]
@racodond Do you see Sass support as part of this issue, or should I open a new one for it?

**Comment by racodond** [comment]
@pascalberger For sure, support of Less and Sass won't be shipped in the same version. But if I manage to overcome the technical issues, especially about rule reusability between CSS and Less, it should be pretty straightforward to add support for Sass after having added support for Less.

It would be great if you can open a new issue to support Sass. What would be even greater is to detail the coding rules you'd like to be implemented for Sass.

**Comment by pascalberger** [comment]
@racodond Done: #12
