### ISSUE TITLE
Add a rule that forbids using types in selectors

### ISSUE THREAD

**Issue by roookeee** [racodond/sonar-css-plugin#68]
I have a use-case where our team wants to disallow SCSS / CSS that styles tags (e.g div) directly.
This includes complex selectors like: 
`div.someClass > div `
`.someOtherClass > .moreClasses div`
I know this rule is controversial, but it has its use-cases for teams that have opinionated coding-guidelines

**Comment by racodond** [comment]
Hi @naze,

I'm not very keen to implement such a rule as it is very opinionated.
Feel free to implement it yourself through a custom plugin. See https://github.com/racodond/sonar-css-plugin#custom-checks. Reopen this ticket if you have any questions during the implementation of this custom plugin.

Cheers

David

**Comment by roookeee** [comment]
The rules:
Shorthand properties should be used whenever possible

Shorthand properties should not be used

Are opinionated too, but like all rules they are not mandatory but prove to be useful like e.g. the rules to forbid id selectors, as styling via tags reduces reuseability too. 

Furthermore we use your plugin within a dockerized sonarqube which makes writing a custom rule very Hard, as we would have to fork and host an adjusted version of your plugin.

**Comment by racodond** [comment]
Hi @naze,

> The rules:
> Shorthand properties should be used whenever possible
> 
> Shorthand properties should not be used
> 
> Are opinionated too, but like all rules they are not mandatory but prove to be useful like e.g. the rules to forbid id selectors, as styling via tags reduces reuseability too.

Fair enough. I don't have that much time to work on it for now. Would you like to try to draft a PR?

> Furthermore we use your plugin within a dockerized sonarqube which makes writing a custom rule very Hard, as we would have to fork and host an adjusted version of your plugin.

You don't need to fork the CSS plugin. Custom rules should be embedded in a dedicated plugin.

Thanks!

David

**Comment by roookeee** [comment]
Thanks, I will get to it next week.

**Comment by roookeee** [comment]
As it stands I will get to do the PR in the next month (30 days), shall I reopen an issue then or do you want to leave this one open?

**Comment by roookeee** [comment]
I have added pullrequest to implement the discussed rule.

**Comment by racodond** [comment]
@naze:
Here's the pull request to master: https://github.com/racodond/sonar-css-plugin/pull/72. Feel free to review it. Changes:
- Removing the activation of the rule in the default quality profile because this rule won't suit everybody
- Fixing integration tests
- Minor improvements on styling and unit tests
- Squashing all commits

**Comment by roookeee** [comment]
Done.
