### ISSUE TITLE
Rule unknown-type-selector should not raise an issue when selector starts with & (referencing parent)

### ISSUE THREAD

**Issue by romaindutartre** [racodond/sonar-css-plugin#7]
Hi,

I'm getting a lot of errors of this type because I'm concatenating class names using the & operator and I would like to know where is the error coming from, if it's a bug or is it normal.

For example this code gives me the error "Remove this usage of the unknown "&-item" type selector." 

`
.nav-top__icons {  
        display: inline-block;  
        margin-left: 10px;  
        &-item {  
            cursor: pointer;  
            display: inline-block;  
            padding: 10px 9px;  
        }  
}  
`

Thank you,
Romain

**Comment by racodond** [comment]
Hi Romain,

Thanks for your feedback!
I'll tune the rule to remove those false positives.

David

**Comment by romaindutartre** [comment]
Thanks for the quick response :)

**Comment by racodond** [comment]
Create two new types of selector: ScssParentReferencingSelector and LessParentReferencingSelector
