### ISSUE TITLE
Add support for stylus language

### ISSUE THREAD

**Issue by josefarinna** [racodond/sonar-css-plugin#70]
Stylus is another language that is compiled to css, it is inspired on scss and less, but with more options to make a more cleaner Style Sheets. [http://stylus-lang.com/](http://stylus-lang.com/)
I think it shouldn't be very complicate as it similar to scss and less.

**Comment by racodond** [comment]
Hi @josefarinna,

I already thought about adding support to stylus because some people already asked me about it. But it would require a lot of work. But if you feel to add support to stylus, feel free to give it a try. I'll support you.

David

**Comment by jolkdarr** [comment]
Hi

Some JavaScript code from https://github.com/stylus/stylus/tree/dev/lib could help (lexer/parser).
