### ISSUE TITLE
scss:unknown-type-selector: Configuration Issues for Custom Components

### ISSUE THREAD

**Issue by fxOne** [racodond/sonar-css-plugin#73]
I have the feeling that this is a stupid question but it looks like I'm unable to add a regex for custom components which works for us.

Exclusion Patter: `fx-.*`

CSS:
```
fx-my-cool-component {
  ...
}
```

I'm still getting the sonar ticket `Unknown type selectors should be removed`.

Any ideas what I'm doing wrong? I have also looked into your tests which were added here which looks similar: https://github.com/racodond/sonar-css-plugin/commit/607af634178e0362bd1b36f2e8d5548ac82727dc

We are using the following Versions:
Sonar-css-plugin: 4.9
SonarQube: 6.5

**Comment by racodond** [comment]
Hi @fxOne,

It is supposed to work fine :-)
Before investigating further, could you please upgrade to version 4.11 and try again?
Are you sure that there is no whitespace before and after your regular expression?

Thanks!

David

**Comment by fxOne** [comment]
We updated yesterday to the latest version and after a rerun the tickets are gone. It's a little bit wired for me as I didn't saw anything related in the release notes but I'm happy now.

Thanks for you help!

**Comment by racodond** [comment]
@fxOne: It's weird indeed... Because, from what I can remember, nothing has been fixed around it. The most important is that it works now :-)
