### ISSUE TITLE
SonarQube Version 6.7 (build 33306) proposes Plugin v3.1 as latest and greatest

### ISSUE THREAD

**Issue by salixzs** [racodond/sonar-css-plugin#74]
Recently upgraded SonarQube Server to Version 6.7 (build 33306), in Plugins section it provides only 3.1 as latest possible Sonar/CSS/LESS version to be installed.
Does plugin need some updating to show up 4.11 version as latest or there is some major glitch somewhere and I need to install it manually?

**Comment by racodond** [comment]
Hi @salixzs,

You'll have to manually install version 11. See https://github.com/racodond/sonar-css-plugin/issues/26.

David
