### ISSUE TITLE
'stroke' and 'stroke-width' properties should no longer be set as 'experimental'

### ISSUE THREAD

**Issue by Myushu** [racodond/sonar-css-plugin#76]
Hello !

On my sccs file all properties `stroke` and `stroke-width` are flagged as Code smell by the role `Experimental properties should not be used`.

Can you explain me why theses twos properties are flagged are experimental when the [css specification](https://www.w3.org/TR/fill-stroke-3/#strokes) doesn't specify it.

Thanks,

**Comment by racodond** [comment]
Hi @Myushu,

Thanks for your feedback!

The CSS specification you're referring to is a working draft, so it's still experimental from the W3C point of view. But "experimental" for this rule does not mean "experimental from the W3C point of view", it means "not supported by popular browsers". See rule description: "This rule also raises an issue when one of the following experimental properties is found. A property is considered as experimental if it is not supported by IE/Edge 11+, Firefox 44+ and Chrome 48+.".

According to https://css-tricks.com/almanac/properties/s/stroke-width/ and https://css-tricks.com/almanac/properties/s/stroke/, it seems that all recent versions of most popular browsers now support those properties. Thus, I will remove the experimental flag from those properties.

David

**Comment by racodond** [comment]
Already fixed since version 4.8: https://github.com/racodond/sonar-css-plugin/commit/61815b050cef3607c916c4a52377e3086cb1e277#diff-88f618b3c9b319b6122615d6b968f8d9
