### ISSUE TITLE
NOSONAR ignored in SCSS file

### ISSUE THREAD

**Issue by jasperroel** [racodond/sonar-css-plugin#79]
One of our rules (!important) has a /* NOSONAR */ tag, but SonarQube still marks this as Tech Debt. We have tried substituting it for a // NOSONAR tag, but it makes no difference.

NOSONAR works on other (CSS/JS) files, but this particular line seems to be constantly reported on.

Version of the platform: Version 6.7 (build 33306)
Version of the CSS / SCSS / Less plugin: 3.1 installed
Source code to reproduce the error: See screenshot

![nosonar ignored scss](https://user-images.githubusercontent.com/1370303/33609736-8bf6ec7c-d9c9-11e7-81d0-82a8f1f2c740.png)

**Comment by racodond** [comment]
Hi @jasperroel,

I cannot reproduce with the latest version (4.12). Could you please give it a try: https://github.com/racodond/sonar-css-plugin/releases/tag/4.12 ?

Thank you

David

**Comment by jasperroel** [comment]
Thank @racodond, that is good to know. I'm trying to locate that update, but I don't see it in our instance:

![no update beyond 3 1](https://user-images.githubusercontent.com/1370303/33626588-590bd638-d9fb-11e7-9f86-dbe40e2e013a.png)

What's the proper way of getting the updated version installed?

**Comment by racodond** [comment]
It is not available in the marketplace. You can manually install it from https://github.com/racodond/sonar-css-plugin/releases/tag/4.12

**Comment by jasperroel** [comment]
Understood. I'm going to ask our SonarQube hoster to install this new version. Thanks for the quick responses! I'll let you know how that goes!

**Comment by racodond** [comment]
OK!

**Comment by jasperroel** [comment]
Yup, that did it. Many thanks! Okay to close :)

**Comment by racodond** [comment]
Cool!
