### ISSUE TITLE
How to point to .stylelintrc file or customized set of rules in sonarqube

### ISSUE THREAD

**Issue by ankitdadhich** [racodond/sonar-css-plugin#81]
Hi,

I am checking for scss files.
By default it applies 80+ rules but I would like to go incremental as code is throwing so many issues.
So I would like to point to .styllintrc files which contains some rules.

Here is my current configuration in team city. But this doesnt work. It applies all rules.

-Dsonar.language=scss
-Dsonar.inclusions=Src/**/*.scss
-Dsonar.configPath= is it right?? Wanna give path to .stylelintrc file or custom way in sonnarqube
-Dsonar.sourceEncoding=UTF-8
%sonar.github.pullRequest%
%sonar.github.repository%

**Comment by racodond** [comment]
Hi @ankitdadhich,

No, there's no way to pass a stylelint config file.
You should create your own SonarQube quality profile to only activate the rules you'd like. You can start from the mapping between the stylelint and the SonarQube rules. See https://github.com/racodond/sonar-css-plugin#stylelint--sonarqube-rule-mapping for more details.

David

**Comment by ankitdadhich** [comment]
Thanks,

Lets say I have created a quality profile named "Custom SCSS Check" (which contains only 10 rules).

How do i configure it in teamcity??
How do I map it in team city with below configuration?

Lets say currently it is pointing to default profile. How can I make it point to "Custom SCSS Check"??

-Dsonar.language=scss
-Dsonar.inclusions=Src/**/*.scss
-Dsonar.sourceEncoding=UTF-8
%sonar.github.pullRequest%
%sonar.github.repository%

**Comment by racodond** [comment]
The link between your project and the quality profile is set through the SonarQube web interface. See https://docs.sonarqube.org/display/SONAR/Project+Settings#ProjectSettings-QualityGateandSettingQualityProfiles
