### ISSUE TITLE
experimental-property-usage: pointer-events supported in IE11

### ISSUE THREAD

**Issue by sidd9433** [racodond/sonar-css-plugin#84]
It seems `pointer-events` is supported in IE11, is it possible to remove the check from the rule?

https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events#Browser_compatibility

**Comment by racodond** [comment]
Hi @sidd9433,

This has been fixed about 6 months ago.
Upgrading to the latest release will fix your issue: https://github.com/racodond/sonar-css-plugin/releases/tag/4.13

David
