### ISSUE TITLE
FP on rule 'Property values should be valid' for value of max-width property

### ISSUE THREAD

**Issue by atvn** [racodond/sonar-css-plugin#86]
Hi all,

Should not check `Property values should be valid` for value `none` of `max-width` property and change the comment max-width: `none|length| ....` instead `auto | <length> | ...`

Please check default value of `max-width` property @ http://www.w3schools.com/cssref/pr_dim_max-width.asp

Thanks.

**Comment by racodond** [comment]
Hi @atvn,

The current implementation of the rule for `max-width` complies to the link you provided. And this link does not mention `auto` in possible values. So, I'm not sure to understand your point...

Could you please elaborate?

Thank you

David

**Comment by atvn** [comment]
Hi @racodond ,

Because when I use `max-width: none`, I got the bug look like:

*Update the invalid value of property "max-width". Expected format: auto | <length> | <percentage> | fill | max-content | min-content | fit-content*

It should not valid because the default of `max-width` property is `none`

Is it clear for you?

Thanks,
An

**Comment by racodond** [comment]
Hi @atvn,

What is the version of your CSS plugin? Because I don't reproduce the issue with the latest version (2.4).

![image](https://cloud.githubusercontent.com/assets/1215713/21794504/19f68942-d6fb-11e6-9480-a559778dbe1e.png)

Thank you

David

**Comment by atvn** [comment]
Hi @racodond ,

wow, I checked with my IT guys, they keep the old version (only 1.4 :( )  right now.

Sorry about this mistake.

Thank you.
An

**Comment by racodond** [comment]
@atvn Time to upgrade then! :-)
