### ISSUE TITLE
Is it possible to add custom rules for SCSS files?

### ISSUE THREAD

**Issue by ankitdadhich** [racodond/sonar-css-plugin#89]
Is it possible to add custom rules for SCSS files?
Is there any sample available for SCSS custom rule?

**Comment by racodond** [comment]
Hi @ankitdadhich,

Yes, this is possible. I updated https://github.com/racodond/sonar-css-custom-rules-plugin accordingly.

David

**Comment by ankitdadhich** [comment]
Hey David, 

Thanks for a quick response. 
I am having bit difficulty in putting custom rule.

Whenever I copy and paste `customrule.jar`  to plugins folder SonarQube crashes.

I tried it plenty of time, it works fine when I remove the `customrule.jar` .

Not sure am I doing anything wrong? very less info is available on internet as well.

Once I do this successfully I will write an step by step article on medium for people.
Will send to you for review purpose.

Thanks
Ankit

**Comment by racodond** [comment]
Hi Ankit,

Could you please open an issue on https://github.com/racodond/sonar-css-custom-rules-plugin?
Where did you get the jar? It's named sonar-css-custom-rules-plugin.jar at https://github.com/racodond/sonar-css-custom-rules-plugin/releases.
Could you please also provide the log file of the version of SonarQube, CSS plugin, the log file of the server, etc.?

Thank you

David
