### ISSUE TITLE
Support for postcss

### ISSUE THREAD

**Issue by NikitaEgorov** [racodond/sonar-css-plugin#90]
Please add support for [Postcss](http://postcss.org/)

**Comment by racodond** [comment]
Hi @NikitaEgorov,

Could you please elaborate?
What are your expectations?

Because the syntax of your CSS files depends on the PostCSS plugins you are using. As they are hundreds of plugins available, they are quite a few syntaxes available...

Thank you

David

**Comment by NikitaEgorov** [comment]
PostCSS already has linter https://github.com/stylelint/stylelint/blob/master/docs/user-guide/postcss-plugin.md

**Comment by racodond** [comment]
stylelint is not a PostCSS linter. It does not lint "PostCSS code". It is a PostCSS plugin that lints CSS, SCSS, ... code. This SonarQube CSS / SCSS / Less plugin does similar things (even better? :-)) as it checks for issues on CSS, SCSS and Less code.

If you think that there are some valuable checks from stylelint that are not implemented in this SonarQube plugin, feel free to list them with some rationale.

Thanks

**Comment by NikitaEgorov** [comment]
@racodond thank you
