### ISSUE TITLE
Need clearer guideline about how to set the Exclusions parameter

### ISSUE THREAD

**Issue by sachabrants** [racodond/sonar-css-plugin#90]
https://github.com/racodond/sonar-css-plugin/blob/f2ed2afd5c610c420e750fe2d7d371595d5b9a08/css-checks/src/main/resources/org/sonar/css/checks/l10n/common/template/unknown-type-selector.html#L37

Is this something we are supposed to set in the Administration page in SonarQube or in the sonar-project.properties file?

**Comment by racodond** [comment]
Hi @sachabrants,

It's a rule. So the 'Exclusions' parameter is a rule parameter.

![image](https://user-images.githubusercontent.com/1215713/37313190-67435b1e-264e-11e8-80d7-01354a24cc25.png)

**Comment by sachabrants** [comment]
Thanks @racodond !
