### ISSUE TITLE
Update rule: Remove this usage of the deprecated "background" system color.

### ISSUE THREAD

**Issue by nickyblissAviva** [racodond/sonar-css-plugin#94]
Currently when background as added as a property of a transition it gets flagged as deprecated system colour.
eg.   transition: background .35s, color .35s;

**Comment by racodond** [comment]
Hi @nickyblissAviva,

I can't reproduce the issue. Which version of the CSS plugin are you using?

Thanks

David

**Comment by nickyblissAviva** [comment]
Looks like we're running 2.1. I'll see if we can get it updated.

**Comment by racodond** [comment]
You should definitely upgrade to the latest version: 3.0.

**Comment by nickyblissAviva** [comment]
Have upgraded to 2.4 as our Sonar instance can't see 3.0 at the moment.

**Comment by racodond** [comment]
3.0 was released yesterday: https://groups.google.com/forum/#!topic/sonarqube/1kShaG1a-_8
SonarSource should add it to the Update Center shortly I guess.
