### ISSUE TITLE
 false positive: css:experimental-property-usage text-decoration

### ISSUE THREAD

**Issue by jessefarinacci** [racodond/sonar-css-plugin#94]
I'm seeing many false positive results for text-decoration property. According to caniuse.com ( https://caniuse.com/#search=text-decoration ) the usage that I have is actually supported: "CSS 2.1 properties (well-supported subset): text-decoration (none | underline | overline | line-through)"

Where in my CSS, I am just using text-decoration: none and text-decoration: underline. Those should not trigger a SonarQube warning. (Not only a warning, but a Major warning, which seems a bit critical..)

Please have this rule be more discriminating for known good properties. Thanks!

**Comment by jessefarinacci** [comment]
We are running SonarQube Version 7.0 (build 36138) with CSS / SCSS / Less plugin v3.1.

**Comment by racodond** [comment]
Hi @jessefarinacci,

Please upgrade to the latest version, 4.14: https://github.com/racodond/sonar-css-plugin/releases/tag/4.14

David

**Comment by jessefarinacci** [comment]
Whoops, sorry about the false positive false positive issue report. :-)

Will this release appear in the typical SonarQube administrator interface? We have a rather large deployment and prefer not to use one-off installs.

**Comment by racodond** [comment]
No problem!

The CSS plugin is no longer available in the SonarQube Marketplace: https://github.com/racodond/sonar-css-plugin/issues/26
