### ISSUE TITLE
Rule case: allow some functions to be written in camel case

### ISSUE THREAD

**Issue by nickyblissAviva** [racodond/sonar-css-plugin#95]
Currently transformation functions in CSS, such as scaleX, translateZ, are all being flagged as needing converting to lowercase however camel case in this instance is completely valid.

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function

**Comment by racodond** [comment]
@nickyblissAviva Camel case, all uppercase or all lowercase is valid for any CSS property as CSS is case-insensitive. This rule is just a naming convention. But I agree that, most of the times, those functions (scaleX, translateZ, etc.) are written in camel case. I'll think about adding some exclusions to this rule and I'll come back to you on this matter.

**Comment by nickyblissAviva** [comment]
Thank you. We are running stylelint as well within our GULP process and if you fix it in one place it then complains in the other.

**Comment by racodond** [comment]
@nickyblissAviva: All the issues you raised are now fixed. Feel free to test the snapshot fixing your issue at https://github.com/racodond/sonar-css-plugin/releases/tag/nickyblissAviva and provide some feedback.

Thanks

David
