### ISSUE TITLE
FP css:validate-property-value on filter

### ISSUE THREAD

**Issue by RubyPaasche** [racodond/sonar-css-plugin#97]
The following filter will cause "css:validate-property-value" violation,  but it should be correct?

` filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);`

**Comment by racodond** [comment]
Hi,

Which version of the CSS plugin are you running?

David

**Comment by RubyPaasche** [comment]
Hi,

sonarqube 7.0 with css-plugin 4.15

**Comment by racodond** [comment]
Hi,

This is deprecated for quite a while, isn't it?

David

**Comment by RubyPaasche** [comment]
As far as I can see no. " -ms-filter" is deprecated in favor of "filter". In IE8 mode " -ms-filter" is a synonym for filter. 

A mistake is the value should be in quotes, as in

`filter: 'progid:DXImageTransform.Microsoft.BasicImage(rotation=3);'`

I will check this.

**Comment by racodond** [comment]
> This topic documents a feature of Visual Filters and Transitions, which is deprecated as of Windows Internet Explorer 9

See https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ms532849(v%3dvs.85)

**Comment by racodond** [comment]
Any feedback?
