### ISSUE TITLE
Exclude the file type css

### ISSUE THREAD

**Issue by vighneshpai-CT** [racodond/sonar-css-plugin#98]
I've a website where in, the CSS files are generated by less files.
Hence sonar is showing 50% of duplication. I would like to exclude the css files and test just the less files. Any idea how this can be done?

**Comment by racodond** [comment]
To exclude those CSS files, see https://docs.sonarqube.org/display/SONAR/Narrowing+the+Focus#NarrowingtheFocus-IgnoreFiles
