### ISSUE TITLE
link to "quick try" doesn't work

### ISSUE THREAD

**Issue by rkarnia** [racodond/sonar-css-plugin#99]
Hi, on Your page, in section "Getting Started in Two Minutes" is link: https://github.com/racodond/package-test-sonarqube-css , but there is 404 error. 

I looking for some examples of using Your plugin, because when I add configuration like:
sonar.css.file.suffixes=.scss
css.sonar.projectName=CSS
css.sonar.language=css
css.sonar.projectBaseDir=.
css.sonar.sources=www/src/scss/

it doesn't work:
INFO: Sensor Embedded CSS Analyzer Sensor [css]
INFO: 0 source files to be analyzed
INFO: Sensor Embedded CSS Analyzer Sensor [css] (done) | time=3ms

Thanks for help !

**Comment by rkarnia** [comment]
ps. I use sonarqube 7.0 with css-plugin 4.15

**Comment by racodond** [comment]
Hi @rkarnia,

Thanks for the feedback! I just removed this section because the repository no longer exists as "Installation Guide" section is enough to get started.

David
